CREATE TABLE course
(
    ID   BIGINT PRIMARY KEY,
    NAME VARCHAR(100)
);

CREATE SEQUENCE course_seq START WITH 1 INCREMENT BY 1;

ALTER TABLE codelab
    ADD FK_COURSE_ID BIGINT;

ALTER TABLE codelab
    ADD CONSTRAINT FK_COURSE_ID FOREIGN KEY (FK_COURSE_ID) REFERENCES course (ID);

ALTER TABLE codelab
    ALTER COLUMN FK_COURSE_ID SET NOT NULL;